micronaut:
  application:
    name: airportService

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/airport-db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: docker

jpa:
  default:
    packages-to-scan:
      - 'com.hkg.micronaut.airport'
    properties:
      hibernate:
      hbm2ddl:
        auto: update
      show_sql: true